//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIDfmContext.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActionLog
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ActionLog()
        {
            this.ActionItems = new HashSet<ActionItems>();
        }
    
        public long Id { get; set; }
        public long アクション { get; set; }
        public System.DateTime 処理開始日時 { get; set; }
        public System.DateTime 処理終了日時 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActionItems> ActionItems { get; set; }
    }
}
