//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIDfmContext.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActionItems
    {
        public long Id { get; set; }
        public long ActionLogId { get; set; }
        public string key { get; set; }
        public string value { get; set; }
        public System.DateTime INSERT_DATE { get; set; }
        public System.DateTime UPDATE_DATE { get; set; }
    }
}
