INSERT INTO [dbo].[Resource] ([Id], [名前], [見出し名]) VALUES (1,'Microsoft .NET Framework','.Net',GETDATE(),GETDATE());
INSERT INTO [dbo].[Resource] ([Id], [名前], [見出し名]) VALUES (2,'Microsoft Excel','Excel',GETDATE(),GETDATE());
INSERT INTO [dbo].[Resource] ([Id], [名前], [見出し名]) VALUES (3,'Microsoft IIS','IIS',GETDATE(),GETDATE());
INSERT INTO [dbo].[Resource] ([Id], [名前], [見出し名]) VALUES (4,'Microsoft Office','Office',GETDATE(),GETDATE());
INSERT INTO [dbo].[Resource] ([Id], [名前], [見出し名]) VALUES (5,'Microsoft PowerPoint','PowerPoint',GETDATE(),GETDATE());
INSERT INTO [dbo].[Resource] ([Id], [名前], [見出し名]) VALUES (6,'Microsoft SQL Server','MS-SQL',GETDATE(),GETDATE());
INSERT INTO [dbo].[Resource] ([Id], [名前], [見出し名]) VALUES (7,'Microsoft ASP.NET MVC','ASP.NET MVC',GETDATE(),GETDATE());
INSERT INTO [dbo].[Resource] ([Id], [名前], [見出し名]) VALUES (8,'Microsoft Windows Server 2008','WinSrv 2008',GETDATE(),GETDATE());
INSERT INTO [dbo].[Resource] ([Id], [名前], [見出し名]) VALUES (9,'Microsoft Windows 2008 R2','WinSrv 2008 R2',GETDATE(),GETDATE());
INSERT INTO [dbo].[Resource] ([Id], [名前], [見出し名]) VALUES (10,'Microsoft Windows Server 2012','WinSrv 2012',GETDATE(),GETDATE());
INSERT INTO [dbo].[Resource] ([Id], [名前], [見出し名]) VALUES (11,'Microsoft Windows Media Services','Windows Media Services',GETDATE(),GETDATE());
INSERT INTO [dbo].[Resource] ([Id], [名前], [見出し名]) VALUES (12,'Microsoft Word','Word',GETDATE(),GETDATE());
INSERT INTO [dbo].[Resource] ([Id], [名前], [見出し名]) VALUES (13,'Apache 2.2','Apache 2.2',GETDATE(),GETDATE());
INSERT INTO [dbo].[Resource] ([Id], [名前], [見出し名]) VALUES (14,'Apache Struts','Struts',GETDATE(),GETDATE());
INSERT INTO [dbo].[Resource] ([Id], [名前], [見出し名]) VALUES (15,'Apache Tomcat JK Connector','JK Connector',GETDATE(),GETDATE());
INSERT INTO [dbo].[Resource] ([Id], [名前], [見出し名]) VALUES (16,'Apache 2.4','Apache 2.4',GETDATE(),GETDATE());
INSERT INTO [dbo].[Resource] ([Id], [名前], [見出し名]) VALUES (17,'Red Hat Enterprise Linux ES 3','RHEL ES3',GETDATE(),GETDATE());
INSERT INTO [dbo].[Resource] ([Id], [名前], [見出し名]) VALUES (18,'Red Hat Enterprise Linux 5','RHEL 5',GETDATE(),GETDATE());
INSERT INTO [dbo].[Resource] ([Id], [名前], [見出し名]) VALUES (19,'Red Hat Enterprise Linux Server 6','RHEL 6',GETDATE(),GETDATE());
INSERT INTO [dbo].[Resource] ([Id], [名前], [見出し名]) VALUES (20,'Red Hat Enterprise Linux Server 7','RHEL 7',GETDATE(),GETDATE());
INSERT INTO [dbo].[Resource] ([Id], [名前], [見出し名]) VALUES (21,'Oracle Database','Oracle',GETDATE(),GETDATE());
INSERT INTO [dbo].[Resource] ([Id], [名前], [見出し名]) VALUES (22,'OpenSSL','OpenSSL',GETDATE(),GETDATE());
INSERT INTO [dbo].[Resource] ([Id], [名前], [見出し名]) VALUES (23,'OpenSSH','OpenSSH',GETDATE(),GETDATE());
INSERT INTO [dbo].[Resource] ([Id], [名前], [見出し名]) VALUES (24,'MySQL','MySQL',GETDATE(),GETDATE());
INSERT INTO [dbo].[Resource] ([Id], [名前], [見出し名]) VALUES (25,'mod_ssl','mod_ssl',GETDATE(),GETDATE());
INSERT INTO [dbo].[Resource] ([Id], [名前], [見出し名]) VALUES (26,'Perl','Perl',GETDATE(),GETDATE());
INSERT INTO [dbo].[Resource] ([Id], [名前], [見出し名]) VALUES (27,'Oracle Java SE JDK','Java SE',GETDATE(),GETDATE());
INSERT INTO [dbo].[Resource] ([Id], [名前], [見出し名]) VALUES (28,'Movable Type','Movable Type',GETDATE(),GETDATE());
INSERT INTO [dbo].[Resource] ([Id], [名前], [見出し名]) VALUES (29,'CakePHP','CakePHP',GETDATE(),GETDATE());
INSERT INTO [dbo].[Resource] ([Id], [名前], [見出し名]) VALUES (30,'jQuery','jQuery',GETDATE(),GETDATE());
INSERT INTO [dbo].[Resource] ([Id], [名前], [見出し名]) VALUES (31,'PostgreSQL','PostgreSQL',GETDATE(),GETDATE());
INSERT INTO [dbo].[Resource] ([Id], [名前], [見出し名]) VALUES (32,'PHP','PHP',GETDATE(),GETDATE());
INSERT INTO [dbo].[Resource] ([Id], [名前], [見出し名]) VALUES (33,'Tomcat','Tomcat',GETDATE(),GETDATE());
INSERT INTO [dbo].[Resource] ([Id], [名前], [見出し名]) VALUES (34,'sendmail','sendmail',GETDATE(),GETDATE());
INSERT INTO [dbo].[Resource] ([Id], [名前], [見出し名]) VALUES (35,'Samba','Samba',GETDATE(),GETDATE());
INSERT INTO [dbo].[Resource] ([Id], [名前], [見出し名]) VALUES (36,'Ruby','Ruby',GETDATE(),GETDATE());
INSERT INTO [dbo].[Resource] ([Id], [名前], [見出し名]) VALUES (37,'sudo','sudo',GETDATE(),GETDATE());
INSERT INTO [dbo].[Resource] ([Id], [名前], [見出し名]) VALUES (38,'Ruby on Rails','Ruby on Rails',GETDATE(),GETDATE());
INSERT INTO [dbo].[Resource] ([Id], [名前], [見出し名]) VALUES (39,'VMware ESXi','VMware ESXi',GETDATE(),GETDATE());
INSERT INTO [dbo].[Resource] ([Id], [名前], [見出し名]) VALUES (40,'Symfony','Symfony',GETDATE(),GETDATE());
INSERT INTO [dbo].[Resource] ([Id], [名前], [見出し名]) VALUES (41,'WordPress','WordPress',GETDATE(),GETDATE());
